#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("iversonc-palindrome");
let palindrome_line = "";

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    palindrome_line += line + '\n';
    console.log("palindrome detected:", line);
  }
});

fs.writeFileSync("palindromes.txt",palindrome_line);
